# Generated by Django 4.0.1 on 2022-01-22 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateTimeField()),
                ('total_members', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('number_of_members', models.IntegerField()),
                ('payment_date', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costsplit.plan')),
            ],
        ),
    ]
