# Generated by Django 4.0.1 on 2022-01-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costsplit', '0002_costs_cost_info_plan_plan_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
