# Generated by Django 4.0.1 on 2022-01-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costsplit', '0005_remove_plan_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('number_of_members', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('cost_info', models.CharField(default=None, max_length=400)),
                ('cost_status', models.BooleanField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costsplit.plan')),
            ],
            options={
                'verbose_name': 'Cost',
                'verbose_name_plural': 'Costs',
            },
        ),
        migrations.DeleteModel(
            name='Costs',
        ),
    ]
