# Generated by Django 4.0.1 on 2022-01-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costsplit', '0006_cost_delete_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cost_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cost',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costsplit.plan'),
        ),
    ]
