# Generated by Django 4.0.1 on 2022-01-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costsplit', '0007_alter_cost_cost_status_alter_cost_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='plan',
        ),
        migrations.AddField(
            model_name='cost',
            name='plan_of_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_plan', to='costsplit.plan'),
        ),
    ]
