# Generated by Django 4.0.1 on 2022-01-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costsplit', '0008_remove_cost_plan_cost_plan_of_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='cost',
            name='plan_of_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costsplit.plan'),
        ),
    ]
